### ISSUE TITLE
'We do not support this language yet' error when trying to use this on C# code within a Unity project - not sure if bug or undocumented intentional behaviour

### ISSUE THREAD

**Issue by 11BelowStudio** [Trelent/Trelent-IntelliJ-Extension#1]
So, just noticed your plugin on the Jetbrains plugin page, and decided to install it for Rider (2022.1), attempted to use it to generate a docstring for a C# file (within a Unity project), and was greeted with the 'We do not support this language yet' error, despite C# apparently being supported.

Not sure if this was an oversight (maybe Rider internally treats C# files within a Unity project as different to normal C# files, causing your tool to not realize that they are C# files), or if this was intentional (like if you're planning on treating C# files within a Unity project differently to ordinary C# files).

Please could you either update the plugin to treat Unity C# files as C# files, or update the description of the plugin to explicitly state that C# files within Unity projects are unsupported? Thanks.

**Comment by calum-bird** [comment]
Hey there, thank you for reporting this. First of all, it's very cool to see Trelent used in the game development space!

To answer your question, this is completely unintentional, and I apologize for the inconvenience this may have caused. I will try to reproduce this tonight, and include a fix in the next build. This should be going out later this week/weekend.

Thanks again!

**Comment by calum-bird** [comment]
Writing again to confirm I found the bug and it will be patched in the next release. We were incorrectly retrieving the language in the opened file, which was returning "C#" instead of "csharp". Fix is live internally, just waiting on a couple bugs to be fixed prior to the next release.

- Calum

**Comment by calum-bird** [comment]
Hi again! Just wanted to drop in and say that we are just awaiting JetBrains approval for the next release to go live. In the meantime you can install Version 1.7.0 (this release) ahead of approval if you would like. I've attached the latest build below.

Thanks again for reporting this bug!

[Trelent - AI Docstrings on Demand-1.7.0.zip](https://github.com/Trelent/Trelent-IntelliJ-Extension/files/8799508/Trelent.-.AI.Docstrings.on.Demand-1.7.0.zip)
