### ISSUE TITLE
Couldn't find Trelent in DataSpell EAP 2023.2

### ISSUE THREAD

**Issue by ntluong95** [Trelent/Trelent-IntelliJ-Extension#16]
I just updated my DataSpell to version EAP 2023.2 and realize that I couldn't find the plugin in the market. Hope you can check and fix it soon

**Comment by calum-bird** [comment]
Hey Luong, thanks for sharing this! Looking into it - sorry for the delay.

**Comment by calum-bird** [comment]
Fixing with next update 1.8.9, which is pending review by Jetbrains team :)
