### ISSUE TITLE
IDE Fatal errors

### ISSUE THREAD

**Issue by mananrvyas** [Trelent/Trelent-IntelliJ-Extension#2]
Every time i try to use the plugin, i get a fatal error ( i tried reinstalling the plugin, still getting the same error)

the ss
<img width="1181" alt="Screenshot 2023-02-02 at 1 40 42 PM" src="https://user-images.githubusercontent.com/98926096/216419673-ea0fccf3-5b34-4ba3-9057-4db965020b99.png">

**Comment by calum-bird** [comment]
Thanks for reporting this! Could I get some additional info about your setup to help debug? In particular:

- Which Jetbrains IDE is being used?
- What version of the IDE is this occurring with?

Thanks again!

**Comment by calum-bird** [comment]
Could you try updating to the newest version (1.8.6)? Let me know if that fixes this!
