### ISSUE TITLE
Generate docstring for the wrong function

### ISSUE THREAD

**Issue by Axl-Lvy** [Trelent/Trelent-IntelliJ-Extension#3]
I have trouble selecting the function I want to generate the docstring for...
![image](https://user-images.githubusercontent.com/81815421/217825852-76cd426a-2bca-40e9-be4b-80664020dfd5.png)
I put my cursor just at the end of "user".
![image](https://user-images.githubusercontent.com/81815421/217825997-9ebed755-3836-4b28-a012-4f24b2964ffc.png)
And it generate (again) the docstring for the function just above. Sometime it is not the function above but another.
What am I doing wrong ?

My IDE : PyCharm 2022.3.2 (Professional Edition)

**Comment by calum-bird** [comment]
Thanks for the bug report! This is definitely not intended, and you aren't doing anything wrong. Will aim to fix asap!

**Comment by calum-bird** [comment]
Hi @Axl-Lvy, could you download the new update (1.8.5) for JetBrains and try again? I believe this should be fixed.

**Comment by Axl-Lvy** [comment]
Hi, for now it seems that the bug is resolved, bravo ! I will let you know if I see it again.
Notice the weird indentation in this screenshot : it's much less important but still, just to let you know ;)
![image](https://user-images.githubusercontent.com/81815421/224231612-65369f80-8d73-4488-b632-4fe0c0e9d238.png)

**Comment by calum-bird** [comment]
Excellent! We're aware of the indentation issues, and this should be fixed sometime in the next month or so. Admittedly lower on the priority list.
