### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Eldrasi** [Trelent/Trelent-IntelliJ-Extension#6]
Hi! Every time I try to generate documentation in IntelliJ IDEA, I get an error, no matter what version of the plugin (currently the latest). At the same time in VSCode everything works fine this plugin

Something went wrong. Please contact support by emailing contact@trelent.net with error id 98c8d7db690a4cfe82524bbabd8b9166. We apologize for the inconvenience.

![image](https://user-images.githubusercontent.com/78851719/225240574-963fb930-6c84-4a93-aaa0-68901b161010.png)

**Comment by calum-bird** [comment]
Found the issue and publishing a fix now! Should be live shortly. For now, TypeScript likely won't work unfortunately.

**Comment by Eldrasi** [comment]
Wow, fust work! Thx!

**Comment by calum-bird** [comment]
Here's the preview that you can install from zip: [https://github.com/Trelent/Trelent-IntelliJ-Extension/releases/tag/v1.8.7](https://github.com/Trelent/Trelent-IntelliJ-Extension/releases/tag/v1.8.7)

JetBrains is reviewing and will publish the update live on the marketplace in the next 12-36 hours. I'll keep this issue until then, but let me know once you get a chance to retry this with the fix in place!

**Comment by calum-bird** [comment]
Now approved by JetBrains and available [here]( https://plugins.jetbrains.com/plugin/18716-trelent--ai-docstrings-on-demand/versions/stable/307388). Closing for now, feel free to re-open if it's still an issue!

**Comment by Eldrasi** [comment]
Still bad 

Something went wrong. Please contact support by emailing contact@trelent.net with error id 2cc1e33cdaa84b9d9a5c06a30b63cd8c. We apologize for the inconvenience.

1.8.8

![image](https://user-images.githubusercontent.com/78851719/227224761-506fbdee-86aa-42a2-9c33-ba04805429d1.png)

И я вижу, что появилась новая индикация создания документации (раньше такого не видел ни разу), но она виснет на половине процесса.

![image](https://user-images.githubusercontent.com/78851719/227225159-ae90eb19-bbdb-463b-b593-03815328d98d.png)
